package me.kalmemarq.minicraft;

import com.mojang.ld22.entity.furniture.FurnitureType;
import com.mojang.ld22.gfx.Color;
import com.mojang.ld22.item.FurnitureItem;
import com.mojang.ld22.item.Item;
import com.mojang.ld22.item.PowerGloveItem;
import com.mojang.ld22.item.ResourceItem;
import com.mojang.ld22.item.ToolItem;
import com.mojang.ld22.item.ToolType;
import com.mojang.ld22.item.resource.FoodResource;
import com.mojang.ld22.item.resource.PlantableResource;
import com.mojang.ld22.item.resource.Resource;
import com.mojang.ld22.level.tile.Tile;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import it.unimi.dsi.fastutil.objects.ObjectList;
import it.unimi.dsi.fastutil.objects.Reference2IntMap;
import it.unimi.dsi.fastutil.objects.Reference2IntOpenHashMap;

import java.util.HashMap;
import java.util.IdentityHashMap;
import java.util.Map;

// TODO: Use dynamic registry
public final class Items {
	public static final Registry<Item> REGISTRY = new Registry<>();

	public static Item WOOD_SHOVEL = REGISTRY.register("wood_shovel", new ToolItem(ToolType.SHOVEL, 0));
	public static Item ROCK_SHOVEL = REGISTRY.register("rock_shovel", new ToolItem(ToolType.SHOVEL, 1));
	public static Item IRON_SHOVEL = REGISTRY.register("iron_shovel", new ToolItem(ToolType.SHOVEL, 2));
	public static Item GOLD_SHOVEL = REGISTRY.register("gold_shovel", new ToolItem(ToolType.SHOVEL, 3));
	public static Item GEM_SHOVEL = REGISTRY.register("gem_shovel", new ToolItem(ToolType.SHOVEL, 4));
	public static Item WOOD_HOE = REGISTRY.register("wood_hoe", new ToolItem(ToolType.HOE, 0));
	public static Item ROCK_HOE = REGISTRY.register("rock_hoe", new ToolItem(ToolType.HOE, 1));
	public static Item IRON_HOE = REGISTRY.register("iron_hoe", new ToolItem(ToolType.HOE, 2));
	public static Item GOLD_HOE = REGISTRY.register("gold_hoe", new ToolItem(ToolType.HOE, 3));
	public static Item GEM_HOE = REGISTRY.register("gem_hoe", new ToolItem(ToolType.HOE, 4));
	public static Item WOOD_PICKAXE = REGISTRY.register("wood_pickaxe", new ToolItem(ToolType.PICKAXE, 0));
	public static Item ROCK_PICKAXE = REGISTRY.register("rock_pickaxe", new ToolItem(ToolType.PICKAXE, 1));
	public static Item IRON_PICKAXE = REGISTRY.register("iron_pickaxe", new ToolItem(ToolType.PICKAXE, 2));
	public static Item GOLD_PICKAXE = REGISTRY.register("gold_pickaxe", new ToolItem(ToolType.PICKAXE, 3));
	public static Item GEM_PICKAXE = REGISTRY.register("gem_pickaxe", new ToolItem(ToolType.PICKAXE, 4));
	public static Item WOOD_AXE = REGISTRY.register("wood_axe", new ToolItem(ToolType.AXE, 0));
	public static Item ROCK_AXE = REGISTRY.register("rock_axe", new ToolItem(ToolType.AXE, 1));
	public static Item IRON_AXE = REGISTRY.register("iron_axe", new ToolItem(ToolType.AXE, 2));
	public static Item GOLD_AXE = REGISTRY.register("gold_axe", new ToolItem(ToolType.AXE, 3));
	public static Item GEM_AXE = REGISTRY.register("gem_axe", new ToolItem(ToolType.AXE, 4));
	public static Item WOOD_SWORD = REGISTRY.register("wood_sword", new ToolItem(ToolType.SWORD, 0));
	public static Item ROCK_SWORD = REGISTRY.register("rock_sword", new ToolItem(ToolType.SWORD, 1));
	public static Item IRON_SWORD = REGISTRY.register("iron_sword", new ToolItem(ToolType.SWORD, 2));
	public static Item GOLD_SWORD = REGISTRY.register("gold_sword", new ToolItem(ToolType.SWORD, 3));
	public static Item GEM_SWORD = REGISTRY.register("gem_sword", new ToolItem(ToolType.SWORD, 4));
	public static Item POWER_GLOVE = REGISTRY.register("power_glove", new PowerGloveItem());
	public static Item WOOD = REGISTRY.register("wood", new ResourceItem(new Resource(1 + 4 * 32,Color.get(-1, 200, 531, 430))));
	public static Item STONE = REGISTRY.register("stone", new ResourceItem(new Resource(2 + 4 * 32, Color.get(-1, 111, 333, 555))));
	public static Item FLOWER = REGISTRY.register("flower", new ResourceItem(new PlantableResource(4 * 32, Color.get(-1, 10, 444, 330), Tile.flower, Tile.grass)));
	public static Item ACORN = REGISTRY.register("acorn", new ResourceItem(new PlantableResource(3 + 4 * 32, Color.get(-1, 100, 531, 320), Tile.treeSapling, Tile.grass)));
	public static Item DIRT = REGISTRY.register("dirt", new ResourceItem(new PlantableResource(2 + 4 * 32, Color.get(-1, 100, 322, 432), Tile.dirt, Tile.hole, Tile.water, Tile.lava)));
	public static Item SAND = REGISTRY.register("sand", new ResourceItem(new PlantableResource(2 + 4 * 32, Color.get(-1, 110, 440, 550), Tile.sand, Tile.grass, Tile.dirt)));
	public static Item CACTUS_FLOWER = REGISTRY.register("cactus_flower", new ResourceItem(new PlantableResource(4 + 4 * 32, Color.get(-1, 10, 40, 50), Tile.cactusSapling, Tile.sand)));
	public static Item SEEDS = REGISTRY.register("seeds", new ResourceItem(new PlantableResource(5 + 4 * 32, Color.get(-1, 10, 40, 50), Tile.wheat, Tile.farmland)));
	public static Item WHEAT = REGISTRY.register("wheat", new ResourceItem(new Resource(6 + 4 * 32, Color.get(-1, 110, 330, 550))));
	public static Item BREAD = REGISTRY.register("bread", new ResourceItem(new FoodResource(8 + 4 * 32, Color.get(-1, 110, 330, 550), 2, 5)));
	public static Item APPLE = REGISTRY.register("apple", new ResourceItem(new FoodResource(9 + 4 * 32, Color.get(-1, 100, 300, 500), 1, 5)));
	public static Item COAL = REGISTRY.register("coal", new ResourceItem(new Resource(10 + 4 * 32, Color.get(-1, 0, 111, 111))));
	public static Item IRON_ORE = REGISTRY.register("iron_ore", new ResourceItem(new Resource(10 + 4 * 32, Color.get(-1, 100, 322, 544))));
	public static Item GOLD_ORE = REGISTRY.register("gold_ore", new ResourceItem(new Resource(10 + 4 * 32, Color.get(-1, 110, 440, 553))));
	public static Item IRON_INGOT = REGISTRY.register("iron_ingot", new ResourceItem(new Resource(11 + 4 * 32, Color.get(-1, 100, 322, 544))));
	public static Item GOLD_INGOT = REGISTRY.register("gold_ingot", new ResourceItem(new Resource(11 + 4 * 32, Color.get(-1, 110, 330, 553))));
	public static Item SLIME = REGISTRY.register("slime", new ResourceItem(new Resource(10 + 4 * 32, Color.get(-1, 10, 30, 50))));
	public static Item GLASS = REGISTRY.register("glass", new ResourceItem(new Resource(12 + 4 * 32, Color.get(-1, 555, 555, 555))));
	public static Item CLOTH = REGISTRY.register("cloth", new ResourceItem(new Resource(1 + 4 * 32, Color.get(-1, 25, 252, 141))));
	public static Item CLOUD = REGISTRY.register("cloud", new ResourceItem(new PlantableResource(2 + 4 * 32, Color.get(-1, 222, 555, 444), Tile.cloud, Tile.infiniteFall)));
	public static Item GEM = REGISTRY.register("gem", new ResourceItem(new Resource(13 + 4 * 32, Color.get(-1, 101, 404, 545))));
	public static Item ANVIL = REGISTRY.register("anvil", new FurnitureItem(FurnitureType.ANVIL));
	public static Item CHEST = REGISTRY.register("chest", new FurnitureItem(FurnitureType.CHEST));
	public static Item FURNACE = REGISTRY.register("furnace", new FurnitureItem(FurnitureType.FURNACE));
	public static Item LANTERN = REGISTRY.register("lantern", new FurnitureItem(FurnitureType.LANTERN));
	public static Item OVEN = REGISTRY.register("oven", new FurnitureItem(FurnitureType.OVEN));
	public static Item WORKBENCH = REGISTRY.register("workbench", new FurnitureItem(FurnitureType.WORKBENCH));
}
